### ISSUE TITLE
naruhiyo アイコン作成

### ISSUE THREAD

**Issue by hiyoko3** [naruhiyo/naruhiyo.github.io#20]
- idea
    - ひよこがらーめんに浸かっている
    - ねこなべならぬひよらー

**Comment by hiyoko3** [comment]
現在考えているのはこんなアイコン。もう一工夫ほしい

![naruhiyo](https://user-images.githubusercontent.com/16721102/66703689-1f4fc980-ed50-11e9-83a7-012471416081.png)

**Comment by narugit** [comment]
かわいすぎるンゴ

**Comment by hiyoko3** [comment]
- 色の相性がよくない

**Comment by hiyoko3** [comment]
一旦作成はしたのでclose
