### ISSUE TITLE
Docker環境の構築

### ISSUE THREAD

**Issue by hiyoko3** [naruhiyo/naruhiyo.github.io#3]
ローカルに作るよりもDockerで開発した方が効率化されるのではないか？

せっかくの機会なのでDockerを学びましょう！

**Comment by hiyoko3** [comment]
フロントのJavaScript環境ではDockerは必要ないかもしれません

**Comment by narugit** [comment]
同意です。
[この記事](https://mizchi.hatenablog.com/entry/2019/04/07/074634)や[この記事](https://lealog.hateblo.jp/entry/2017/04/26/105447)を読んで、フロント開発にDockerは必要ないと思いました。
