### ISSUE TITLE
Reactのライブラリ導入

### ISSUE THREAD

**Issue by hiyoko3** [naruhiyo/naruhiyo.github.io#6]
- [x] [react-router](https://github.com/ReactTraining/react-router)
- [redux](https://github.com/reduxjs/redux)
    - ポートフォリオ程度に設計思想は入れなくてもいい気はする
- [x] [react-i18next](https://github.com/i18next/react-i18next)

**Comment by hiyoko3** [comment]
redux は @narugit と打ち合わせをして導入を検討する

**Comment by narugit** [comment]
reduxに関して、今回作成するポートフォリオには、現状、reduxを採用するほどのStoreを使用しないため、必要ないと思います。
